### PR TITLE
Massively cleaned and improved C version

### PR DESCRIPTION
**Pull request by 9x14S**
I did some refactoring to remove repetitive code and useless functions, also added a big global buffer so that it won't be needed to create many small ones when calling functions and added some better error checking.

 - Added support for Linux and MacOS (didn't test it on MacOS, but theoretically should be the same)
 - Cleaned up the code and used better styling.
 - Removed a few irrelevant functions.
 - Made other functions able to handle both image and video processing.
 - Split error output to `stderr` and normal output to `stdout`.
 - Removed a few irrelevant `system()`.
 - Changed the weird `strcat()`/`memcpy()` string manipulation to `snprintf()`.
 - User input should be sanitized before being passed to `system()`, if all shells behave the same (text in single quotes is escaped)
 - Fixed some typos.
 - Added better checks for availability of tools. Now it checks if the tools are installed system-wide.
 
To-do: 
- Handle user input sanitization in PowerShell if the quotes fix doesn't apply.
- Find a way to remove the `system()` calls.
- Add multiple file handling.
- Remove `exiftool` and `ffmpeg` output when being called.
- Add option to actually see what's the metadata, instead of only removing it.
- Find a way to get file data like size without the `fopen, fseek, ftell` approach.

Some ideas for further improvement:
- Make the program work by passing arguments and options, instead of the interactive approach.
- Maybe add color to the output.
- Add support for more file formats.
- Maybe add multiprocessing/threading if there are many files.

### CODE REVIEW

**Comment by 9x14S** [comment]
Second group of changes, this time to the Python version:
- Cleaned up a lot of the code, of all files.
- Removed a lot of redundant functions.
- Removed many `if os.name == "nt"` checks and replaced them with a `setup` function in `commons.py`.
- Fixed some `cls` display bugs and other more general bugs.
- Added better input handling for the `menu` function.
- Added more checks inside functions.
- Also removed useless checks in other functions.
- Made a few functions more general, working for both images and videos.

Pending: 
- Adding documentation.
- Removing `__main__.py` file, given that is isn't used.
- Removing `__init__.py` or making the program a PyPI package.
- Changing some internal strings so that they won't interfere with potential files (changing `output.txt` to `<random name>.mtd)
- Possibly adding functionality from `tempfile`.
- Possibly removing the `os.system` call to `mat2` to instead import and internally use its functions.
- Find a way to check availability of dependencies without having to use `os.system`.
- Do some more debugging (help needed on this)
- Improve portability.
- Improve installation instructions (both for the C and Python version).

Suggestions:
- Migrate from the interactive approach to a command line one. (Might need to fork this into a POSIX-like-only version)
- Package it as a PyPI package.
- Remove the `os.system` calls completely.

Also, I would like to get feedback on my `setup` function approach, and if it is preferably to the "lots of `if os.name == `" approach it had before.

**Comment by Anish-M-code** [comment]
@evil-user kindly review this PR.

**Comment by 9x14S** [comment]
Adding a warning: Probably doesn't work in Windows yet. I'm still looking at it but I can't test it.

**Comment by Anish-M-code** [comment]
Thanks for Contributing @9x14S

**Pull request merged**
