### PR TITLE
Create PyPi package

### PR DESCRIPTION
**Pull request by CalebUsadi**
I've significantly reorganized the codebase and modified the Python code to make it a Python package. It can be packaged using the instructions [Packaging Python Projects](https://packaging.python.org/en/latest/tutorials/packaging-projects/).

### CODE REVIEW

**Comment by Anish-M-code** [comment]
@CalebUsadi thanks for the amazing work , could you please merge changes made in pull request #9 it would improve the efficiency of code. I guess from glancing code in _ _ main _ _ .py the program will exit after one of cases in match  have been executed so encapsulating that menu code in a recursive function or while true (preferred ) will ensure program keeps running till user exits.

**Review by Anish-M-code — COMMENTED** [review]
Also in file commons.py in function cls( ) , i think one liner os.system('cls' if platform.system().lower() == 'windows' else 'clear') would be fine. This would ensure we don't need extra function sys()

**Comment by CalebUsadi** [comment]
Can do. I'm currently on another computer and having build issues on Windows due to PyGObject being a dependency of mat2 by way of cairo, so my next changes will be untested.

**Comment by Anish-M-code** [comment]
@CalebUsadi i guess mat2 cannot be directly used as a dependency as it contains linux specific code , i 
 have tried to compile it for windows but faced issues too  reference https://0xacab.org/jvoisin/mat2/-/issues/175.

so what i have done is created a patched version of libmat2 which works in windows with reduced features. i guess while packaging MRT python package , libmat2 can be packaged along with it , installing mat2 via pip in windows is a pain.

**Comment by CalebUsadi** [comment]
I believe it's working correctly and ready for merge. I haven't tested all of the options, but I'm about to.

**Comment by CalebUsadi** [comment]
The first and second options work. The third and fourth options are broken because there is no MRT directory. I think the behavior of this should be changed anyway, I'll dig into it. And the fifth and sixth have strange things happening as well.

**Comment by Anish-M-code** [comment]
@CalebUsadi  I am currently unable to build this package due to windows issue , could you please upload your build to https://test.pypi.org so that i could check how to fix it.

**Comment by Anish-M-code** [comment]
@CalebUsadi  I am currently unable to build this package due to windows issue , could you please upload your build to https://test.pypi.org so that i could check and try to fix breakage if possible.

**Comment by CalebUsadi** [comment]
I can't upload it at the moment, but it can easily be built locally. Do the following in a virtualenv. Let me know if you have any questions!
```
pip install build
build
py -m install /dist/[name_of_file]
py -m metadata_remover
```

**Comment by Anish-M-code** [comment]
Thanks for contributing @CalebUsadi  👍

**Pull request merged**
