### PR TITLE
Hey I barely know how to use GitHub, but I did my best to remove bloat and make the code more concise

### PR DESCRIPTION
**Pull request by 9x14S**
Changes: 
-Made lists of the functions used in each .py file outside libmat2 folder
-Removed as much bloat and unnecessary code as I could
-Fixed typos and weird formatting
-Might have broken something, as I couldn't test it by myself

### CODE REVIEW

**Comment by 9x14S** [comment]
(I really recommend checking if the code actually works. Sorry for not knowing how to use git and GitHub)

**Comment by Anish-M-code** [comment]
Thank you for contributing @9x14S , will check and merge mostly by next sunday.

**Comment by Anish-M-code** [comment]
@evil-user kindly review this PR has been present since a long time. kindly speedup the reviewing process .

**Comment by evil-user** [comment]
Sorry @9x14S @Anish-M-code , I couldn't review it on time due to health issues , We would like to merge some parts of PR would you like to open the PR agaiin @9x14S , we value every contribution here , i am sorry we couldn't respond on time.

**Comment by 9x14S** [comment]
Hey @evil-user. I'll make some changes and improvements and then post a PR as soon as I can. Thanks for your time

**Pull request closed without merging**
